name: 05-02-filter-activity-types

on:
    pull_request:
        types:
            - closed

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is closed"
